---
abstract: 'Perl Client for Selenium Remote Driver'
author:
  - 'Aditya Ivaturi <ivaturi@gmail.com>'
  - 'Daniel Gempesaw <gempesaw@gmail.com>'
  - 'Luke Closs <cpan@5thplane.com>'
  - 'Mark Stosberg <mark@stosberg.com>'
build_requires:
  File::Basename: '0'
  File::stat: '0'
  FindBin: '0'
  IO::Socket::INET: '0'
  LWP::Simple: '0'
  Test::Exception: '0'
  Test::LWP::UserAgent: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Selenium-Remote-Driver
requires:
  Archive::Extract: '0'
  Archive::Zip: '0'
  Carp: '0'
  Cwd: '0'
  Data::Dumper: '0'
  Exporter: '0'
  File::Copy: '0'
  File::Temp: '0'
  HTTP::Headers: '0'
  HTTP::Request: '0'
  HTTP::Response: '0'
  IO::Compress::Zip: '0'
  IO::Socket: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  Moo: '1.005'
  Moo::Role: '0'
  Net::Ping: '0'
  Scalar::Util: '0'
  Sub::Install: '0'
  Test::Builder: '0'
  Test::LongString: '0'
  Try::Tiny: '0'
  base: '0'
  constant: '0'
  namespace::clean: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/gempesaw/Selenium-Remote-Driver/issues
  repository: git://github.com/gempesaw/Selenium-Remote-Driver.git
version: '0.2201'
x_contributors:
  - 'Allen Lew <allen@alew.org>'
  - 'Bas Bloemsaat <bas@bloemsaat.com>'
  - 'Brian Horakh <brianh@zoovy.com>'
  - 'Charles Howes <charles.howes@globalrelay.net>'
  - 'Daniel Fackrell <dfackrell@bluehost.com>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Dmitry Karasik <dmitry@karasik.eu.org>'
  - 'Emmanuel Peroumalnaik <eperoumalnaik@weborama.com>'
  - 'Eric Johnson <eric.git@iijo.org>'
  - 'Gabor Szabo <gabor@szabgab.com>'
  - 'Gordon Child <gordon@gordonchild.com>'
  - 'GreatFlamingFoo <greatflamingfoo@gmail.com>'
  - 'Ivan Kurmanov <duraley@gmail.com>'
  - 'Joe Higton <draxil@gmail.com>'
  - 'Jon Hermansen <jon.hermansen@gmail.com>'
  - 'Ken Swanson <kswanson@genome.wustl.edu>'
  - 'Phil Kania <phil@vivox.com>'
  - 'Phil Mitchell <phil.mitchell@pobox.com>'
  - 'Robert Utter <utter.robert@gmail.com>'
  - 'Tom Hukins <tom@eborcom.com>'
  - 'Vishwanath Janmanchi <jvishwanath@gmail.com>'
  - 'amacleay <a.macleay@gmail.com>'
  - 'jamadam <sugama@jamadam.com>'
